### ISSUE TITLE
RegistrationStrategy throw exception type

### ISSUE THREAD

**Issue by recepakyuz** [khellang/Scrutor#113]
Hi,
I like this library but I scare multi implementation.
Can you make an improvement.
If app find multi implementation at registering, Throw exception.

**Comment by khellang** [comment]
Sure, that should be pretty easy. Can I ask why you're worried about multiple registrations for a single service? 🤔

**Comment by khellang** [comment]
Pushed a new version to NuGet with this feature 😊

**Comment by dasMulli** [comment]
Thanks for implementing that, it just saved me from hours of debugging.
Use case: having a dynamic IView<TTarget,TSource>() registrations (basically mapping with logic but not a good fit for automapper, also some magic wrapping instances for APM tracing and some magic using the type system so users can't use invalid combinations). in the process of refactoring it turned out that some hard dependencies on converter types caused registrations for the same type - and it would have been hard to spot that while testing
