### ISSUE TITLE
Does Scrutor support conditional registrations, mixed open/closed registrations, and some advanced usages?

### ISSUE THREAD

**Issue by 82amp** [khellang/Scrutor#157]
I am a SimpleInjector (SI) user, but looking to move to .Net5 DI and use Scrutor to fill some gaps. The main gap is in Decorators, which is obvious. There are a few other SI features that I require, and I'm not sure if Scrutor supports them.

First is "conditional registrations", or fallback registrations when no other registered generic type matches
https://docs.simpleinjector.org/en/latest/advanced.html#registration-of-open-generic-types

Second is mixing open/closed generics registrations
https://docs.simpleinjector.org/en/latest/advanced.html#mixing-collections-of-open-generic-and-non-generic-components

Thanks

**Comment by khellang** [comment]
Hi @82amp! 👋🏻 

> First is "conditional registrations", or fallback registrations when no other registered generic type matches

I'm not familiar with conditional registrations. It's not something that's supported today, but it looks like it could be implemented, but only at registration time. The underlying container does not pass the required information at resolve-time.

> Second is mixing open/closed generics registrations

Mixing open/closed generics _is_ supported by Microsoft's container, but I'm not sure whether your specific scenarios would be. You probably just have to test it.

Scrutor is basically trying to cover some gaps in Microsoft's built-in container, but there are some things that we just can't fix due to lack of support in the underlying container. We do have some decoration support, but it's pretty poor and might not work in all cases you're used to from SimpleInjector. You sound like you use quite a few advanced features, so I'd probably advice you to keep using SimpleInjector if you rely on these.
