### ISSUE TITLE
Is the Scrutor project dead? 😞

### ISSUE THREAD

**Issue by dario-l** [khellang/Scrutor#219]
Is the Scrutor project dead? 😞 

- Last commit 9 months ago 😢 
- Last release on Mar 27, 2023 😭

**Comment by khellang** [comment]
Of course it's not dead. That's such an awful take on a perfectly healthy free open source project with active open PRs. I have a life, work, family, renovating a house and other stuff going on. Please don't come around with that kind of entitlement.

**Comment by dario-l** [comment]
Sorry for my sneaky issue like this but... as all can see You easly found a time to respond to this but not for others questions. I really understand your situation but... maintaining open-source project (that project which is widely used) is also some kind of responsibility. IMHO responding is one of fundamental one.

Happy Christmas 🎄

**Comment by khellang** [comment]
> as all can see You easly found a time to respond to this but not for others questions

I'm not sure what questions you're referring to, but it's probably because this was a 1 minute answer and the other question(s) require A LOT more time to answer, if I can answer them at all.

> maintaining open-source project (that project which is widely used) is also some kind of responsibility

Again, I won't have entitlement like that in my free open source repos. This is not how open source works. One more time and you're blocked. We don't have a contract. You're not paying me anything. I don't owe you anything. If you don't like it, the project is MIT licensed and free to fork.
