### ISSUE TITLE
Support for interceptor

### ISSUE THREAD

**Issue by moattarwork** [khellang/Scrutor#24]

**Comment by khellang** [comment]
Hey! 

First of all, it would be cool if this issue was a bit more descriptive. I'm not 100% sure on what you mean by "interceptor".

Second, I'm not sure this is the right library for interception (if it means what I think it means). They're a whole lot of work, and this library is meant to be a small, focused library on top of Microsoft.Extensions.DependencyInjection. If you want full-blown container features like this, you're better off using an awesome container like Autofac or StructureMap.
