### ISSUE TITLE
Strongly name assembly

### ISSUE THREAD

**Issue by mattfrear** [khellang/Scrutor#53]
My project is using SignAssembly in its .csproj:
```
  <PropertyGroup>
    <VersionPrefix>4.0.0</VersionPrefix>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>key.snk</AssemblyOriginatorKeyFile>
    <DelaySign>False</DelaySign>
  </PropertyGroup>
```
When I compile, I get a warning
```
Referenced assembly 'Scrutor, Version=2.2.2.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
```

Could you sign the assembly in the NuGet package please?

**Comment by khellang** [comment]
I could probably strong name it if someone sent a pull request. I've never strong named an assembly in my life and I believe it's totally unnecessary, but if someone cares enough and wants to do the work, I'd be willing to accept a PR. Or you could just use [StrongNamer]( https://github.com/dsplaisted/strongnamer)

**Comment by mattfrear** [comment]
Yeah, I had never strong named anything in my life either, until someone requested that I strong name my Swashbuckle.AspNetCore.Filters package (which now uses Scrutor).

I'm not too fussed really, I can ignore a compiler warning, and it doesn't seem to affect usage of my package. Close this issue if you like.

**Comment by khellang** [comment]
Cool! I have to take a look at it when I have time. I'll leave it open in case someone feel like contributing 😊

**Comment by khellang** [comment]
Will push a release within the next hour or so 👍

**Comment by khellang** [comment]
v3.0.0 is now [on NuGet](https://www.nuget.org/packages/Scrutor/3.0.0) :smile:

**Comment by danstur** [comment]
@khellang Not sure if this would be better as a separate issue, but one problem with strong naming is that if you do it "wrong" people get into troubles.

In my experience the best way to deal with this is to make sure the AssemblyVersion is *always* `Major.0.0` (or more general one single version that is not changed throughout development of the version). This is what Microsoft does with their assemblies too. 

The reason is simple: Assuming you follow semantic versioning 3.1.0 should be compatible with 3.0.0. If you change the AssemblyVersion this is *not* the case though, since libraries who reference 3.0.0 can't deal with 3.1.0. 

Most problems with strong naming and why it has such a bad rep come down to this (or people getting semver wrong). Would you accept a PR that explicitly sets the AssemblyVersion? Probably best to leave it at 3.0.2 for 3.x to minimize disturbance.

PS: And yes the whole shebang is annoying and rarely worth the trouble, but sadly some projects have requirements outside our control that require strong named assemblies.

**Comment by khellang** [comment]
> Would you accept a PR that explicitly sets the AssemblyVersion?

Yes, absolutely. I didn't even think of version number pinning 😏
