### ISSUE TITLE
NU3008 package integrity check failed

### ISSUE THREAD

**Issue by dungtri** [khellang/Scrutor#60]
Hello,

I got this error with one guy's laptop on my team, after he try to restore or install again the nuget package for scrutor 3.0.1, he got this error :

_package integrity check failed._

Description of the nuget error is available here : 
https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3008

I don't reproduce the problem on my machine or another colleague laptop. Really strange... We all use VS 2017 with the lastest service package 15.7.1.

Actions we already try to solve the problem :
- Clean nuget cache on nuget package option in visual studio & by running `nuget locals -Clear all`
- Clean .vs, bin, obj folders & try to rebuild again.

The problem is only for the v3.0.1, for v2.2.2 that's work.

Could you check on you side if change hasn't be made on nuget spec.

Thanks for helping.

Kind regards,

Dung Tri.

**Comment by khellang** [comment]
> Could you check on you side if change hasn't be made on nuget spec.

But there *has* been an intentional change to the package; it's now strong named.

I made a mistake when signing and releasing v3.0, which is why I had to release v3.0.1 right after. I've updated to the v3.0.1 package in multiple projects and they all run fine.

I'm not sure what to do about this... 🤔

**Comment by chbohm** [comment]
I have the same issue. 
I need to install scruptor 3.0.1 in our own nuget server but it fails! I tried the same steps with 2.2.2 and everything went ok...

I have also tried this: I downloaded both versions into my computer, and I tried to unzip them. I could unzip 2.2.2 but 3.0.1 says it is corrupt:

C:\Users\cbohm\Desktop\Scrutor\scrutor.3.0.1.nupkg.zip: Checksum error in 
C:\Users\cbohm\Desktop\Scrutor\scrutor.3.0.1.nupkg\Scrutor.nuspec. The file is corrupt
C:\Users\cbohm\Desktop\Scrutor\scrutor.3.0.1.nupkg.zip: The archive is corrupt


 I could verify the the only file that is corrupt in 3.0.1 is: Scrutor.nuspec

**Comment by khellang** [comment]
> but it fails!

What does that mean? Any details? I have nothing to go on here...

**Comment by chbohm** [comment]
Could you try unziping Scrutor.3.0.1.nupkg? It unzips everything except Scrutor.nuspec which it says it is corrupt. I think this is the problem that make fail the installation of this package into my own nuget repo.

Here I am pasting the error log, but I think it will add noise rather than help you, 

{
  "message": "An error has occurred.",
  "exceptionMessage": "File contains corrupted data.",
  "exceptionType": "System.IO.FileFormatException",
  "stackTrace": "   at MS.Internal.IO.Zip.ProgressiveCrcCalculatingStream.Read(Byte[] buffer, Int32 offset, Int32 count)\r\n   at MS.Internal.IO.Zip.ZipIOModeEnforcingStream.Read(Byte[] buffer, Int32 offset, Int32 count)\r\n   at System.Xml.XmlTextReaderImpl.InitStreamInput(Uri baseUri, String baseUriStr, Stream stream, Byte[] bytes, Int32 byteCount, Encoding encoding)\r\n   at System.Xml.XmlTextReaderImpl.FinishInitStream()\r\n   at System.Xml.XmlReaderSettings.CreateReader(Stream input, Uri baseUri, String baseUriString, XmlParserContext inputContext)\r\n   at System.Xml.XmlReader.Create(Stream input, XmlReaderSettings settings, String baseUri)\r\n   at NuGet.XmlUtility.LoadSafe(Stream input, Boolean ignoreWhiteSpace)\r\n   at NuGet.Manifest.ReadFrom(Stream stream, IPropertyProvider propertyProvider, Boolean validateSchema)\r\n   at NuGet.Lucene.FastZipPackage.ProcessManifest(Stream manifestStream)\r\n   at NuGet.Lucene.FastZipPackage.Open(String fileLocation, Stream stream, Byte[] hash)\r\n   at NuGet.Lucene.FastZipPackage.Open(String fileLocation, Byte[] hash)\r\n   at NuGet.Lucene.Web.Formatters.PackageFormDataMediaFormatter.ReadFormDataFromStreamAsync(HashingMultipartFileStreamProvider streamProvider)\r\n   at NuGet.Lucene.Web.Formatters.MultipartFormDataMediaFormatter`2.<ReadFromStreamAsync>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Net.Http.HttpContentExtensions.<ReadAsAsyncCore>d__0`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.ModelBinding.FormatterParameterBinding.<ExecuteBindingAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.HttpActionBinding.<ExecuteBindingAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at NuGet.Lucene.Web.MessageHandlers.CrossOriginMessageHandler.<SendAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()"
} 
But the package looks fine when I open it in nuget package explorer.
I also managed to upload an earlier version 2.2.2 successfully.

**Comment by khellang** [comment]
I wonder if this is a tooling issue. See https://github.com/dotnet/corefx/issues/25803. I can try to bump the version and push a new package to see if that changes anything.

**Comment by chbohm** [comment]
yes please! it seems that the problem is the one it is posted in  dotnet/corefx#25803.Can you try what you said?thanks!
    El viernes, 9 de noviembre de 2018 11:31:49 ART, Kristian Hellang <notifications@github.com> escribió:  
 
 
I wonder if this is a tooling issue. See dotnet/corefx#25803. I can try to bump the version and push a new package to see if that changes anything.

**Comment by khellang** [comment]
I've pushed a new version, v.3.0.2, where all I did was bump the version number and push a new package. Hopefully that fixes it 🤞🏻

**Comment by khellang** [comment]
Any feedback on this?

**Comment by pitming** [comment]
We are facing same problem on our CI... Scrutor package is corrupted

**Comment by khellang** [comment]
Since I haven't heard any feedback on this since releasing 3.0.2 (and knowing that people successfully run 3.0.2), I'm closing this.
