### ISSUE TITLE
Registering/resolving decorator without registering base implementation

### ISSUE THREAD

**Issue by julealgon** [khellang/Scrutor#90]
I need a very specific requirement and I'm failing to see how to make it work using Scrutor, if it is even possible at all.

I have a factory class responsible for instantiating some `IHandler`-type interface instances. This factory takes runtime data to build each instance, so we cannot register it directly in the container as the factory for `IHandler` (we have to inject `IHandlerFactory` instead and call it from the consumer). This factory manually creates the instances, so the container is not involved in this step.

So far so good.

Now, I want to decorate `IHandler` instances with a `LoggingHandler` implementation. The problem here is that I can't use `Decorate<IHandler, LoggingHandler>` because I'm not resolving `IHandler` from the container to begin with.

My current solution is to inject a `Func<IHandler, IHandler>` into the factory to allow it to decorate the instances it creates, but this is not flexible enough because I have to be very specific when registering this func:

```
                .AddTransient<Func<IHandler, IHandler>>(
                    provider => (handler) => new LoggingHandler(
                        handler,
                        provider.GetRequiredService<ILogger>()));
```

This works fine, but as you can see I now have to specify all dependencies of the decorator explicitly on registration.

Is there a way to resolve the func directly without having to register a base implementation? I'd rather have this:
```
                .Decorate<IHandler, LoggingHandler>();
```
And then have my constructor resolve correctly:
```
public HandlerFactory(Func<IHandler, IHandler> decoratorFunction)
{
   …
}
```

**Comment by khellang** [comment]
Right, the `Decorate` method needs a `ServiceType` that has existing service descriptors registered in the collection to loop through them and perform some voodoo magic to make decoration work, so there's no way to what you're asking with the current `Decorate` method.

What you could do, is look into `ActivatorUtilities.CreateInstance`, which `Decorate` uses internally, to do what you're after. You'd essentially have to write your own `Decorate` method that registers `Func<IHandler, IHandler>` instead of `IHandler` itself.
